node:
  name: "alice"
  level: 1
  genesis-hash: "0x0000000"
  cluster-head-grpc-address:
  grpc:
    address: "localhost:50050"
    timeout: 1m

storage:
  directory: "volumes/alice"

logger:
  mode: "dev"
  log-level: "debug"
  log-format: "text"
  with-caller: false
  colored: true

worker-pool:
  max-workers: 10
  max-capacity: 100

schedulers:
  sync:
    enabled: false
    interval: 1m
    start-immediately: false

  explore:
    enabled: false
    interval: 1h
    start-immediately: false
