node:
  name: "alice"
  level: 0
  genesis-hash: "0x0000000"
  is-cluster-head: false
  cluster-head-grpc-address:
  nodes-grpc-addresses: []
  wait-block:
    timeout: 1m
    interval: 1s
  grpc:
    address: "localhost:50050"
    timeout: 1m

storage:
  directory: "volumes/alice"

logger:
  mode: "dev"
  log-level: "debug"
  log-format: "text"
  with-caller: true
  colored: true

schedulers:
  sync:
    enabled: true
    interval: 1m
    immediate: true

  mine:
    enabled: true
    interval: 5s
    immediate: true

  explore:
    enabled: true
    interval: 1h
    immediate: true
