node:
  name: "alice"
  level: 0
  genesis-hash: "0x0000000"
  cluster-head-grpc-address:
  grpc:
    address: "localhost:50050"
    timeout: 1m

storage:
  directory: "volumes/alice"

logger:
  mode: "dev"
  log-level: "debug"
  log-format: "text"
  with-caller: true
  colored: true

worker-pool:
  max-workers: 10
  max-capacity: 100

schedulers:
  sync:
    enabled: true
    interval: 1m
    immediate: true

  explore:
    enabled: true
    interval: 1h
    immediate: true
