meta:
  name: "alice"

node:
  level: 0
  genesis-hash: "0x0000000"
  is-cluster-head: false
  cluster-head-grpc-address:
  nodes-grpc-addresses: []
  query-timeout: 15s

storage:
  directory: "volumes/alice"

logger:
  mode: "dev"
  log-level: "debug"
  log-format: "text"
  with-caller: true
  colored: true

grpc-server:
  port: 50050
  timeout: 15s
